[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = ["pip install -r requirements.txt", "go install github.com/fogleman/primitive@latest"]

[start]
cmd = "export PATH=$PATH:/root/go/bin && uvicorn main:app --host 0.0.0.0 --port $PORT"
